In [1]:
import numpy as np
import theano
import theano.tensor as T
rng = np.random

In [ ]:
N = 400                                   # training sample size
feats = 784                               # number of input variables

# generate a dataset: D = (input_values, target_class)
D = (rng.randn(N, feats), rng.randint(size=N, low=0, high=2))
training_steps = 10000

In [2]:
from itertools import product

data = []

for i in product(np.arange(0,5), np.arange(0,5)):
    data.append([i[0], i[1], 2*(i[0]**2) - 3*(i[1]**2) + 1])
    
data = np.array(data)

#x = data[:,[0,1]]
#y = data[:,2]

In [ ]:


# Declare Theano symbolic variables
x = T.dmatrix("x")
y = T.dvector("y")

# initialize the weight vector w randomly
#
# this and the following bias variable b
# are shared so they keep their values
# between training iterations (updates)
w = theano.shared(rng.randn(2), name="w")

# initialize the bias term
b = theano.shared(0., name="b")

print("Initial model:")
print(w.get_value())
print(b.get_value())



In [ ]:
training_steps = 10000

prediction = T.dot(x, w) + b
costIndv = (prediction - y)**2 
cost = T.sum(costIndv)
gw, gb = T.grad(cost, [w,b])

train = theano.function(
    inputs = [x,y],
    outputs = [prediction, costIndv],
    updates = ((w, w-0.1*gw), (b, b-0.1*gb))
)
predict = theano.function(inputs = [x], outputs = prediction)

for i in range(training_steps):
    pred, err = train(data[:,[0,1]], data[:,2])
    if i % 500 == 0: #only print the cost every 500 epochs/iterations (to save space)
        print('Cost: %s' % (err,))





In [9]:
import numpy
import theano
import theano.tensor as T
rng = numpy.random

#N = 400                                   # training sample size
#feats = 784                               # number of input variables

# generate a dataset: D = (input_values, target_class)
#D = (rng.randn(N, feats), rng.randint(size=N, low=0, high=2))
training_steps = 10000

# Declare Theano symbolic variables
x = T.dmatrix("x")
y = T.dvector("y")

# initialize the weight vector w randomly
#
# this and the following bias variable b
# are shared so they keep their values
# between training iterations (updates)
w = theano.shared(rng.randn(2), name="w")

# initialize the bias term
b = theano.shared(0., name="b")

print("Initial model:")
print(w.get_value())
print(b.get_value())

# Construct Theano expression graph
#p_1 = 1 / (1 + T.exp(-T.dot(x, w) - b))   # Probability that target = 1
#prediction = p_1 > 0.5                    # The prediction thresholded
#xent = -y * T.log(p_1) - (1-y) * T.log(1-p_1) # Cross-entropy loss function
#cost = xent.mean() + 0.01 * (w ** 2).sum()# The cost to minimize
#gw, gb = T.grad(cost, [w, b])             # Compute the gradient of the cost
                                          # w.r.t weight vector w and
                                          # bias term b
                                          # (we shall return to this in a
                                          # following section of this tutorial)

prediction = T.dot((x**2),w) + b
xent = (prediction - y)**2
cost = xent.sum()
gw, gb = T.grad(cost, [w,b])
                
                # Compile
train = theano.function(
          inputs=[x,y],
          outputs=[prediction, xent],
          updates=((w, w - 0.0001 * gw), (b, b - 0.0001 * gb)))
predict = theano.function(inputs=[x], outputs=prediction)

# Train
for i in range(100000):
    pred, err = train(data[:,[0,1]], data[:,2])
    
#x = data[:,[0,1]]
#y = data[:,2]

print("Final model:")
print(w.get_value())
print(b.get_value())
print("target values for D:")
print(data[:,2])
print("prediction on D:")
print(predict(data[:,[0,1]]))

Initial model:
[ 0.48972425 -0.3355455 ]
0.0
Final model:
[ 2. -3.]
1.0
target values for D:
[  1  -2 -11 -26 -47   3   0  -9 -24 -45   9   6  -3 -18 -39  19  16   7
  -8 -29  33  30  21   6 -15]
prediction on D:
[  1.00000000e+00  -2.00000000e+00  -1.10000000e+01  -2.60000000e+01
  -4.70000000e+01   3.00000000e+00  -4.18554080e-14  -9.00000000e+00
  -2.40000000e+01  -4.50000000e+01   9.00000000e+00   6.00000000e+00
  -3.00000000e+00  -1.80000000e+01  -3.90000000e+01   1.90000000e+01
   1.60000000e+01   7.00000000e+00  -8.00000000e+00  -2.90000000e+01
   3.30000000e+01   3.00000000e+01   2.10000000e+01   6.00000000e+00
  -1.50000000e+01]


In [36]:
def layer(x, w):
    b = np.array(np.repeat(1,data[:,[0,1]].shape[0]).reshape(-1,1), dtype = theano.config.floatX)
    new_x = T.concatenate([b, x], axis=1)
    m = T.dot(w, new_x.T).T #theta1: 3x3 * x: 3x1 = 3x1 ;;; theta2: 1x4 * 4x1
    h = nnet.relu(m)
    return h

import numpy
import theano
import theano.tensor as T
rng = numpy.random

#N = 400                                   # training sample size
#feats = 784                               # number of input variables

# generate a dataset: D = (input_values, target_class)
#D = (rng.randn(N, feats), rng.randint(size=N, low=0, high=2))
training_steps = 10000

# Declare Theano symbolic variables
x = T.dmatrix("x")
y = T.dvector("y")

# initialize the weight vector w randomly
#
# this and the following bias variable b
# are shared so they keep their values
# between training iterations (updates)
theta1 = theano.shared(np.array(np.random.rand(3,3), dtype=theano.config.floatX), name = 'theta1')
theta2 = theano.shared(np.array(np.random.rand(4,1), dtype=theano.config.floatX), name = 'theta2')

# initialize the bias term

print("Initial model:")
print(theta1.get_value())
print(theta2.get_value())
#print(b.get_value())

# Construct Theano expression graph
#p_1 = 1 / (1 + T.exp(-T.dot(x, w) - b))   # Probability that target = 1
#prediction = p_1 > 0.5                    # The prediction thresholded
#xent = -y * T.log(p_1) - (1-y) * T.log(1-p_1) # Cross-entropy loss function
#cost = xent.mean() + 0.01 * (w ** 2).sum()# The cost to minimize
#gw, gb = T.grad(cost, [w, b])             # Compute the gradient of the cost
                                          # w.r.t weight vector w and
                                          # bias term b
                                          # (we shall return to this in a
                                          # following section of this tutorial)

#np.concatenate([np.repeat(1,data[:,[0,1]].shape[0]).reshape(-1,1), data[:,[0,1]]], axis=1)
new_x = T.concatenate([np.repeat(1,data[:,[0,1]].shape[0]).reshape(-1,1), x], axis=1)
prediction = T.dot((new_x**2),w)
xent = (prediction - y)**2
cost = xent.sum()
gw= T.grad(cost, w)

h = layer(x, theta1)
prediction = layer(x, theta2)
xent = (prediction - y)**2
cost = xent.sum()
gw = T
                
                # Compile
train = theano.function(
          inputs=[x,y],
          outputs=[prediction, xent],
          updates=[(w, w - 0.0001 * gw)])
predict = theano.function(inputs=[x], outputs=prediction)

# Train
for i in range(100000):
    pred, err = train(data[:,[0,1]], data[:,2])
    
#x = data[:,[0,1]]
#y = data[:,2]

print("Final model:")
print(w.get_value())
print(b.get_value())
print("target values for D:")
print(data[:,2])
print("prediction on D:")
print(predict(data[:,[0,1]]))

Initial model:
[-0.70401986  0.68193498  0.58770806]
Final model:
[ 1.  2. -3.]
0.0
target values for D:
[  1  -2 -11 -26 -47   3   0  -9 -24 -45   9   6  -3 -18 -39  19  16   7
  -8 -29  33  30  21   6 -15]
prediction on D:
[  1.00000000e+00  -2.00000000e+00  -1.10000000e+01  -2.60000000e+01
  -4.70000000e+01   3.00000000e+00  -3.81916720e-14  -9.00000000e+00
  -2.40000000e+01  -4.50000000e+01   9.00000000e+00   6.00000000e+00
  -3.00000000e+00  -1.80000000e+01  -3.90000000e+01   1.90000000e+01
   1.60000000e+01   7.00000000e+00  -8.00000000e+00  -2.90000000e+01
   3.30000000e+01   3.00000000e+01   2.10000000e+01   6.00000000e+00
  -1.50000000e+01]


In [10]:
a = np.array([2,3])

In [12]:
b = np.array([a,4])

array([array([2, 3]), 4], dtype=object)

In [34]:
np.concatenate([np.repeat(1,data[:,[0,1]].shape[0]).reshape(-1,1), data[:,[0,1]]], axis=1)

array([[1, 0, 0],
       [1, 0, 1],
       [1, 0, 2],
       [1, 0, 3],
       [1, 0, 4],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 3],
       [1, 1, 4],
       [1, 2, 0],
       [1, 2, 1],
       [1, 2, 2],
       [1, 2, 3],
       [1, 2, 4],
       [1, 3, 0],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 3],
       [1, 3, 4],
       [1, 4, 0],
       [1, 4, 1],
       [1, 4, 2],
       [1, 4, 3],
       [1, 4, 4]])

In [38]:
np.repeat(1,data[:,[0,1]].shape[0]).reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [29]:
new_x = T.concatenate(x, np.repeat(1,data[:,[0,1]].shape[0]))

TypeError: ("The 'tensors' argument must be either a tuple or a list, make sure you did not forget () or [] around arguments of concatenate.", x)